# Default values for joomla-inetpub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Shared values for all charts
##
global:
  secrets:
    # Name of Joomla secret
    dbuserPassword: "mysql-secret"
  ## Database name (JOOMLA_DB_NAME / MYSQL_DATABASE)
  dbname: "joomla_db"
  ##
  ## JOOMLA_DB_USER / MYSQL_USER
  dbuser: "j210"
  ##
## JOOMLA_DB_HOST
joomlaDbHost: "joomla-mysql"

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: joomla
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "php8.3-apache"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: LoadBalancer
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80
  ## loadBalancerIP for the Joomla Service
  loadBalancerIP: ""

#### Set container requests and limits for resources
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
##
resources:
  enableLimit: false
  limits:
    memory: "768Mi"
    cpu: "500m"
  enableRequest: true
  requests:
    memory: "256Mi"
    cpu: "250m"

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
  
## MySQL specific configuration
mysql:
  ## This sets the container image for MySQL
  ## ref: https://hub.docker.com/_/mysql
  ##
  image:
    repository: "mysql"
    tag: "8.0"
    pullPolicy: IfNotPresent
  ## Tiemzone
  timezone: "Europe/Copenhagen"    
  ##
  #### Set container requests and limits for resources
  ##
  resources:
    enableLimit: false
    limits:
      memory: "768Mi"
      cpu: "500m"
    enableRequest: true
    requests:
      memory: "512Mi"
      cpu: "250m"
