apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: joomla
  name: joomla
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: joomla
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: joomla
    spec:
      containers:
        - env:
            - name: JOOMLA_ADMIN_EMAIL
              value: joomla@example.com
            - name: JOOMLA_ADMIN_PASSWORD
              value: joomla@secured
            - name: JOOMLA_ADMIN_USER
              value: Joomla Hero
            - name: JOOMLA_ADMIN_USERNAME
              value: joomla
            - name: JOOMLA_DB_HOST
              value: db
            - name: JOOMLA_DB_NAME
              value: joomla_db
            - name: JOOMLA_DB_PASSWORD
              value: examplepass
            - name: JOOMLA_DB_USER
              value: joomla
            - name: JOOMLA_SITE_NAME
              value: Joomla
          image: joomla
          name: joomla
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: joomla-data
      restartPolicy: Always
      volumes:
        - name: joomla-data
          persistentVolumeClaim:
            claimName: joomla-data
