---
apiVersion: v1
kind: Service
metadata:
  name: joomla
  namespace: joomla
  labels:
    app: joomla
spec:
  ports:
    - port: 80
  selector:
    app: joomla
  type: LoadBalancer
  loadBalancerIP: 192.168.1.76