---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joomla-data
  namespace: joomla
  labels:
    app: joomla
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi