---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-joomla
namespace: joomla
resources:
  - namespace.yaml
  - configmap.yaml
  - mysql-secret.yaml
  - mysql-service.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - joomla-pvc.yaml
  - joomla-service.yaml
  - joomla-deployment.yaml