---
apiVersion: v1
kind: Service
metadata:
  name: joomla-mysql
  namespace: joomla
  labels:
    app: joomla
spec:
  ports:
  - port: 3306
  selector:
    app: joomla
    tier: mysql
  clusterIP: None